### ISSUE TITLE
Hello supercrafter100

### ISSUE THREAD

**Issue by soypeto** [supercrafter100/Nameless-Store-Paymentwall-Gateway#1]
Hello bro, my name is Humberto and I wanted to see if I could create the Nequi Bancolombia payment method or something like that, it would be great, I hope your prompt response.

**Comment by soypeto** [comment]
Or just like other web pages that put payments are cards, that option would also be super good :)

**Comment by supercrafter100** [comment]
Stripe (a built-in gateway) already supports card payments?

**Comment by soypeto** [comment]
I have no idea bro here in Colombia Stripe is not used sorry if maybe I don't make myself understand what happens is that he speaks Spanish and I'm using the translator
